# Generated by Django 4.0.3 on 2022-05-03 18:21

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('compras', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.BooleanField(default=True)),
                ('fc', models.DateTimeField(auto_now_add=True)),
                ('fm', models.DateTimeField(auto_now=True)),
                ('um', models.IntegerField(blank=True, null=True)),
                ('descripcion', models.CharField(help_text='Descripción de la Categoria', max_length=100, unique=True)),
                ('uc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Categorias',
            },
        ),
        migrations.CreateModel(
            name='Marca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.BooleanField(default=True)),
                ('fc', models.DateTimeField(auto_now_add=True)),
                ('fm', models.DateTimeField(auto_now=True)),
                ('um', models.IntegerField(blank=True, null=True)),
                ('descripcion', models.CharField(help_text='Descripción de la Marca', max_length=30, unique=True)),
                ('uc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Marcas',
            },
        ),
        migrations.CreateModel(
            name='Moneda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.BooleanField(default=True)),
                ('fc', models.DateTimeField(auto_now_add=True)),
                ('fm', models.DateTimeField(auto_now=True)),
                ('um', models.IntegerField(blank=True, null=True)),
                ('descripcion', models.CharField(help_text='Descripción de la Marca', max_length=30, unique=True)),
                ('simbolo', models.CharField(help_text='Simbolo de la Moneda', max_length=3, unique=True)),
                ('compras', models.IntegerField(default=0, help_text='Valor de compras', validators=[django.core.validators.RegexValidator('^[0-9+]', 'Only digit characters.')])),
                ('ventas', models.IntegerField(default=0, help_text='Valor de ventas', validators=[django.core.validators.RegexValidator('^[0-9+]', 'Only digit characters.')])),
                ('maestra', models.BooleanField(default=False, help_text='Moneda Maestra')),
                ('uc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Monedas',
            },
        ),
        migrations.CreateModel(
            name='SubCategoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.BooleanField(default=True)),
                ('fc', models.DateTimeField(auto_now_add=True)),
                ('fm', models.DateTimeField(auto_now=True)),
                ('um', models.IntegerField(blank=True, null=True)),
                ('descripcion', models.CharField(help_text='Descripción de la Sub Categoria', max_length=100)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inv.categoria')),
                ('uc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Sub Categorias',
                'unique_together': {('categoria', 'descripcion')},
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.BooleanField(default=True)),
                ('fc', models.DateTimeField(auto_now_add=True)),
                ('fm', models.DateTimeField(auto_now=True)),
                ('um', models.IntegerField(blank=True, null=True)),
                ('codigo_barra', models.CharField(help_text='Código de Barra', max_length=50, unique=True)),
                ('descripcion', models.CharField(help_text='Descripción del producto', max_length=200)),
                ('imagen', models.ImageField(blank=True, help_text='Imagen', null=True, upload_to='fotos/')),
                ('detalle', models.CharField(blank=True, help_text='Detalle', max_length=250, null=True)),
                ('unidad', models.CharField(help_text='Unidad de Medidas', max_length=3)),
                ('existencia_inicial', models.FloatField(default=0, help_text='Existencia Inicial')),
                ('existencia_actual', models.FloatField(blank=True, default=0, help_text='Existencia Actual', null=True)),
                ('precio_costo', models.FloatField(default=0, help_text='Precio Costo')),
                ('precio_venta', models.FloatField(default=0, help_text='Precio Venta')),
                ('descuento_maximo', models.FloatField(default=0, help_text='Descuentos Máximo')),
                ('incremento_precio_credito', models.FloatField(default=0, help_text='Incremento Precio Crédito')),
                ('ultima_compra', models.DateField(blank=True, help_text='Fecha de Ultima Compra', null=True)),
                ('iva_valor', models.IntegerField(default=10)),
                ('marca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inv.marca')),
                ('moneda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inv.moneda')),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='compras.proveedor')),
                ('subcategoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inv.subcategoria')),
                ('uc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Productos',
            },
        ),
    ]
