# Generated by Django 4.0.3 on 2022-05-03 18:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Compras',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.BooleanField(default=True)),
                ('fc', models.DateTimeField(auto_now_add=True)),
                ('fm', models.DateTimeField(auto_now=True)),
                ('um', models.IntegerField(blank=True, null=True)),
                ('factura_numero', models.CharField(help_text='Factura N°', max_length=20)),
                ('factura_fecha', models.DateField()),
                ('factura_tipo', models.PositiveSmallIntegerField(choices=[(1, 'Contado'), (2, 'Créditos')], default=1)),
                ('factura_total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
            ],
            options={
                'verbose_name_plural': 'Compras',
            },
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.BooleanField(default=True)),
                ('fc', models.DateTimeField(auto_now_add=True)),
                ('fm', models.DateTimeField(auto_now=True)),
                ('um', models.IntegerField(blank=True, null=True)),
                ('documento', models.CharField(help_text='RUC y/o CI N°', max_length=20, unique=True)),
                ('razonsocial', models.CharField(help_text='Razón Social', max_length=100)),
                ('direccion', models.CharField(blank=True, help_text='Dirección', max_length=200, null=True)),
                ('contacto', models.CharField(help_text='Contacto', max_length=100)),
                ('telefono', models.CharField(blank=True, help_text='Teléfono', max_length=10, null=True)),
                ('email', models.CharField(blank=True, help_text='Teléfono', max_length=250, null=True)),
                ('uc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Proveedores',
            },
        ),
        migrations.CreateModel(
            name='ComprasDetalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.BooleanField(default=True)),
                ('fc', models.DateTimeField(auto_now_add=True)),
                ('fm', models.DateTimeField(auto_now=True)),
                ('um', models.IntegerField(blank=True, null=True)),
                ('cantidad', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('iva_valor', models.DecimalField(choices=[(1, 0), (2, 5), (3, 10)], decimal_places=2, default=3, max_digits=4)),
                ('precio_costo', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('precio_venta', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_iva', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('compras', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='compras.compras')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='compras.proveedor')),
                ('uc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'ComprasDetalles',
            },
        ),
    ]
